[package]
name = "thunderus-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30"
crossterm = "0.29"
unicode-width = "0.2"
syntect = { version = "5.2", features = ["default-fancy"] }
owo-colors = "4.1"

thunderus-core = { path = "../core" }
